:schedule:
  BridgeJob:
    cron: '0 2 * * Mon'
    queue: default
    enabled: true
  AverageScoreUpdateJob:
    cron: '0 7 * * Mon'
    queue: default
    enabled: true
  WeeklyScoreUpdateJob:
    cron: '0 9 * * Mon'
    queue: default
    enabled: true
