contribution:
  steps:
    1:
      title: "Pourquoi contribuer ?"
      text: "Réduire notre impact est une priorité. En habitant en France nous n’avons presque aucune chance d’en annuler la totalité, et atteindre l'objectif de l'accord de Paris prendra du temps. Soutenir des projets qui sequestrent ou évitent nos émissions est une première étape, probablement imparfaite, pour assumer notre responsabilité."
